 - numpy stands for numerical python.
 - Allows us to create arrays and perform vectorization
 - vectorization applys operations to all the elements of a collection without an explict loop

In [1]:
import numpy as np

In [2]:
lst = [10,20,30,50,90,100]

In [3]:
a = np.array(lst)
print(a)

[ 10  20  30  50  90 100]


In [4]:
type(a)

numpy.ndarray

All elements in a numpy array should be of the same type

In [ ]:
#numpy simplifies applying operations on every element,
# suppose i want to multiply 10 to every element of the array

In [5]:
print(a*10)

[ 100  200  300  500  900 1000]


In [6]:
#Gives me a boolean array
#in array a if the element > 50, True, Else, False
a>50

array([False, False, False, False,  True,  True])

In [ ]:
#numpy simplifies filtering operations,
# suppose i want to get all elements > 50

In [ ]:
# numpy array can be subsetted through a condition

In [7]:
a[a>50]

array([ 90, 100])

In [8]:
#Shape of the array
a.shape

(6,)

In [9]:
#dimensions of the array
a.ndim

1

In [10]:
#Array auto coerces the elements into a single type
b = np.array(["hi",10,"30",True,4.5])
b

array(['hi', '10', '30', 'True', '4.5'], dtype='<U32')

In [11]:
c = np.array([10,20,True,False,True,50,60])
print(c)

[10 20  1  0  1 50 60]


In [13]:
#list within a list gives a 2d array or a matrix
d = np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(d.ndim)
print(d.shape)

2
(2, 3)


### Generating numpy array using arange

In [15]:
#1.
print(np.arange(5))
print(np.arange(1,10))
print(np.arange(2,10,3))

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[2 5 8]


In [16]:
#2.
#For dimension >1 specify the shape as a tuple for the ones function
print(np.ones(4))
print(np.ones((2,3)))
print(np.ones((2,3,3)))

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
#3.
print(np.zeros(4))
print(np.zeros((2,3)))
print(np.zeros((2,3,3)))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### Mathematical operations on numpy array

In [18]:
x = np.array([2, 4, 7, 10, 12])

In [19]:
print("Sum :", x.sum())

Sum : 35


In [20]:
print("Product :", x.prod())

Product : 6720


In [21]:
print("Min :", x.min()) 

Min : 2


In [22]:
print("Max :", x.max()) 

Max : 12


In [23]:
print("Average :",x.mean())

Average : 7.0


In [24]:
print("Cumulative sum:",x.cumsum())

Cumulative sum: [ 2  6 13 23 35]


In [25]:
print("Standard dev is:", x.std())

Standard dev is: 3.687817782917155


In [26]:
print("Median element is: ", np.median(x))

Median element is:  7.0


In [27]:
print("Max element is at position ", x.argmax())

Max element is at position  4


In [28]:
print("Min element is at position ", x.argmin())

Min element is at position  0


### Subsetting a numpy array

In [29]:
a1d = np.array([10,20,30,40,50,70,90,100])

In [30]:
a1d[0:3]

array([10, 20, 30])

In [31]:
a1d[-1]

100

In [32]:
#array[start:end(exclusive):step]
a1d[0:6:2]

array([10, 30, 50])

In [33]:
#Reverses the array
a1d[::-1]

array([100,  90,  70,  50,  40,  30,  20,  10])

In [34]:
a2d = np.array([[10,20,1],[7,8,75]])
a2d

array([[10, 20,  1],
       [ 7,  8, 75]])

In [35]:
print(a2d[0,1])

20


In [36]:
print(a2d[:,2]) #all elements from 3rd column

[ 1 75]


In [37]:
print(a2d[1,:]) #all elements from the 2nd row

[ 7  8 75]


### Subsetting Task : Given a 2d array 2d array, 

1. Subtract every element by the mean
2. Find all the elements below the mean

In [38]:
a2d = np.array([[10,20,1],[7,8,75]])
print(a2d)

[[10 20  1]
 [ 7  8 75]]


In [39]:
print(np.mean(a2d))

20.166666666666668


In [40]:
print(a2d-np.mean(a2d))

[[-10.16666667  -0.16666667 -19.16666667]
 [-13.16666667 -12.16666667  54.83333333]]


In [41]:
a2d < np.mean(a2d)

array([[ True,  True,  True],
       [ True,  True, False]])

In [42]:
a2d[a2d < np.mean(a2d)]

array([10, 20,  1,  7,  8])