In [1]:
import numpy as np

numpy array operations:

    1. matrix multiplication
    2. transpose
    3. flatten
    4. reshape

### 1. Matrix maultiplication

In [2]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[1,2],[3,4]])

In [3]:
mat1@mat2

array([[ 7, 10],
       [15, 22]])

The columns of the first matrix should be equal to the rows of the second matrix

In [4]:
np.matmul(mat1,mat2)

array([[ 7, 10],
       [15, 22]])

below function does not perform matrix multiplication, it does element by element multiplication of np array

In [5]:
np.multiply(mat1,mat2)

array([[ 1,  4],
       [ 9, 16]])

In [6]:
mat1*mat2

array([[ 1,  4],
       [ 9, 16]])

### 2. Transpose
Transpose of a matrix, where rows will be converted into columns. mXn matrix will be transposed into nXm matrix

In [7]:
a  = np.array([[1,2,3,4]])

In [8]:
a.shape

(1, 4)

In [9]:
a.ndim

2

In [10]:
np.transpose(a)

array([[1],
       [2],
       [3],
       [4]])

In [11]:
np.transpose(mat1)

array([[1, 3],
       [2, 4]])

### 3.Flatten
Flatten converts higher dim array into 1 d

In [12]:
a = np.array([[1,2,3],[4,5,6]])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [13]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 3. Reshape
Converts the array to a specified shape

In [19]:
a = np.array([1,2,3,4,5,6,7,8])
a.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
a.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
a = np.array([10,20,30,40])

In [16]:
a.reshape(2,2)

array([[10, 20],
       [30, 40]])

In [17]:
#Converting into a row matrix
a.reshape(1,4)

array([[10, 20, 30, 40]])

In [18]:
#Converting into a column matrix
a.reshape(4,1)

array([[10],
       [20],
       [30],
       [40]])

In [21]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [22]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])